//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Admin.@__diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnMeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColumnMeta()
        {
            this.TableMetas = new HashSet<TableMeta>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public int DataType { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public int OrderNo { get; set; }
        public bool DisplayInGrid { get; set; }
        public string EnumTypeName { get; set; }
        public bool IsForeignKey { get; set; }
        public bool IsPrimaryKey { get; set; }
        public Nullable<int> ReferenceTableId { get; set; }
        public int TableId { get; set; }
    
        public virtual TableMeta TableMeta { get; set; }
        public virtual TableMeta TableMeta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableMeta> TableMetas { get; set; }
    }
}
