//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Admin.@__diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ModuleType { get; set; }
        public string ScaffoldEntity { get; set; }
        public string TableName { get; set; }
        public int OrderNo { get; set; }
        public string Url { get; set; }
        public int GroupId { get; set; }
        public bool ShowInLeftMenu { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
