//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Admin.@__diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMetaRelation
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int ChildId { get; set; }
        public string ForeignKeyName { get; set; }
        public string Caption { get; set; }
        public bool IsRendered { get; set; }
    
        public virtual TableMeta TableMeta { get; set; }
        public virtual TableMeta TableMeta1 { get; set; }
    }
}
