//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Admin.@__diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableMeta()
        {
            this.ColumnMetas = new HashSet<ColumnMeta>();
            this.ColumnMetas1 = new HashSet<ColumnMeta>();
            this.TableMetaRelations = new HashSet<TableMetaRelation>();
            this.TableMetaRelations1 = new HashSet<TableMetaRelation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public string SchemaName { get; set; }
        public int AppId { get; set; }
        public Nullable<int> LookUpDisplayId { get; set; }
    
        public virtual App App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnMeta> ColumnMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnMeta> ColumnMetas1 { get; set; }
        public virtual ColumnMeta ColumnMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableMetaRelation> TableMetaRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableMetaRelation> TableMetaRelations1 { get; set; }
    }
}
