using System.ComponentModel.DataAnnotations;

namespace DotWeb
{
    /// <summary>
    /// Represents module type: generated from DotWeb engine, or custom URL.
    /// </summary>
    public enum ModuleType
    {
        AutoGenerated,
        CustomUrl
    }

    /// <summary>
    /// Module represents a single page of an application. Which is also represents a menu item in left
    /// navigation control.
    /// </summary>
    public class Module
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        public Module()
        {
            ShowInLeftMenu = true;
        }

        /// <summary>
        /// Id of module, auto-generated.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Title of module which is displayed on the left menu navigation.
        /// Initially the value is taken from Name property, but it can be changed later in
        /// web admin.
        /// </summary>
        [Required, MaxLength(100)]
        public string Title { get; set; }

        /// <summary>
        /// Module type: AutoGenerated or CustomUrl.
        /// </summary>
        public ModuleType ModuleType { get; set; }

        /// <summary>
        /// TODO: future version will incorporate scaffolding, not just autogeneration.
        /// Currently this property is not used.
        /// </summary>
        [MaxLength(100)]
        public string ScaffoldEntity { get; set; }

        /// <summary>
        /// Name of the table if ModuleType == Autogenerated.
        /// </summary>
        [MaxLength(100)]
        public string TableName { get; set; }

        /// <summary>
        /// Order number in left menu navigation.
        /// </summary>
        public int OrderNo { get; set; }

        /// <summary>
        /// If ModuleType == CustomUrl, the Url is provided here.
        /// </summary>
        [MaxLength(100)]
        public string Url { get; set; }

        /// <summary>
        /// If you don't want this group to show in left menu navigation, set this to false.
        /// </summary>
        public bool ShowInLeftMenu { get; set; }

        /// <summary>
        /// The group Id which this module belongs to.
        /// </summary>
        public int GroupId { get; set; }

        /// <summary>
        /// This property is related to <see cref="GroupId"/> property.
        /// </summary>
        public virtual Group Group { get; set; }

        /// <summary>
        /// String representation of module.
        /// </summary>
        /// <returns>String, should match the Title property.</returns>
        public override string ToString()
        {
            return Title;
        }
    }
}
